### ISSUE TITLE
Discussie omtrent aanpassen bestellingen

### ISSUE THREAD

**Issue by cmitz** [csvalpha/sofia#164]
In eerste instantie was het helemaal niet mogelijk om bestellingen te wijzigen. Dit is mogelijk gemaakt werd toen duidelijk werd dat saldomutaties niet de goede manier zijn om het goed in de boekhouding te kunnen verwerken. 

Twan's voorstel was om bestellingen append-only te maken. Dan kan je nooit wijzigen, maar corrigeren met bijvoorbeeld `-1 * fris`. Dit hoef je in de presentatielaag nooit te laten zien, maar los je op binnen Rails.

Ik ben daar wat tegen, omdat het best wat complexiteit met zich meebrengt. Ook wil ik zo transparant mogelijk zijn als het gaat om wat er in de achtergrond in Rails gebeurt en wat er wordt weergegeven. Dat zou inwerktijd en nadenktijd over de boekhouding zoveel mogelijk moeten beperken.

**Comment by Matthijsy** [comment]
Aangezien we op dit moment nog niks doen met eindtotalen, en aangezien we (nog) geen performance issues hebben kunnen we dit denk ik voor nu wel sluiten. Mee eens? @cmitz
