### ISSUE TITLE
Tomato 'rebranden' naar S.O.F.I.A.

### ISSUE THREAD

**Issue by cmitz** [csvalpha/sofia#167]
SOFIA: Streepsysteem voor de Ordentelijke Festiviteiten van Inleggend Alpha

- [ ] Logo Steven erin zetten
  - [x] Homescreen
  - [x] Menu
  - [ ] Emails
- [ ] Nieuwe error pagina's

**Comment by Matthijsy** [comment]
Progress @cmitz ? Volgens mij is dit klaar
