### ISSUE TITLE
Speciaal Bier Promo

### ISSUE THREAD

**Issue by djtjp** [csvalpha/sofia#170]
Als gebruiker wil ik kunnen zien wat voor speciaalbier er momenteel geschonken wordt in Flux. Ik wordt hierdoor sneller verleid door al dat lekkere bier om naar Flux toe te komen

**Comment by Matthijsy** [comment]
Ik denk niet dat dit gaat werken, gaat niemand bij houden en Sofia lijkt me niet de juiste plek. Daarom sluit ik dit issue
