### ISSUE TITLE
Permissies houden geen rekening met vanaf-datum

### ISSUE THREAD

**Issue by cmitz** [csvalpha/sofia#196]
Not sure how or why, maar een vanaf-datum wordt nog niet gehandhaafd bij toekennen rechten adhv 'memberships'.

het gaat denk ik hier mis: https://github.com/csvalpha/alpha-tomato/blob/staging/lib/omniauth/strategies/banana_oauth2.rb#L22
icm https://github.com/csvalpha/alpha-tomato/blob/staging/app/models/user.rb#L65

**Comment by Matthijsy** [comment]
I cannot reproduce this issue. Might be fixed already? @cmitz can you reproduce, otherwise I will close
