### ISSUE TITLE
Soms worden inleggingen niet geregistreerd (sentry)

### ISSUE THREAD

**Issue by cmitz** [csvalpha/sofia#197]
https://sentry.io/csvalpha/alpha-tomato-production/issues/557334470/?query=is:unresolved

Bente appte me 'in paniek' dat een aantal registraties niet waren doorgekomen. Mij is een raadsel waarom, maar het lijkt op deze error (zie sentry).

**Comment by Matthijsy** [comment]
Heb dit issue niet meer voorbij zien/horen komen, daarom sluit ik het issue
