### ISSUE TITLE
Sneltoetsen (keyboard shortcuts) in streepscherm

### ISSUE THREAD

**Issue by cmitz** [csvalpha/sofia#20]
De wens komt neer vanuit de volgende gedachte: zo min mogelijk tijd bezig zijn met het streepsysteem om sneller biertjes te kunnen tappen. Dit wordt onder andere gedaan door niet te wisselen tussen toetsenbord en muis/touchscreen.

Om het streepsysteem met alleen het keyboard te kunnen bedenken moeten er meer shortcuts in het streepscherm waar Ruben de volgende alvast voorstelde op het forum:
- ESC met focus in zoekvlak reset de input
- ENTER is hetzelfde als "Bestelling plaatsen"
- ESC deselecteerd de huidig geselecteerde gebruiker
- Andere shortcuts om items toe te voegen

Ruben over keyboard shortcuts:
<img width="677" alt="afbeelding" src="https://user-images.githubusercontent.com/5594436/38431598-099fcabc-39c5-11e8-9e3c-0ddafcf46a52.png">

Ik wilde verder voorstellen om aan elke categorie een letter te hangen, en dán pas te nummeren van 1 naar 9 (of 0). Het belangrijkste hier is overigens dat shortcuts nooit veranderen. "Muscle memory"

**Comment by Matthijsy** [comment]
Is dit nog zinnig? Het toetsenbord is tegenwoordig niet echt fijn meer en het touchscreen werkt best wel prima

**Comment by cmitz** [comment]
Ja, het is goed voor nu. Dat toetsenbord in Flux is ook niet relaxt. Dan gaan we het nu toch niet bouwen.
