### ISSUE TITLE
Meerdere keren op knop drukken veroorzaakt meerdere keren inleggen

### ISSUE THREAD

**Issue by wilco375** [csvalpha/sofia#377]
Hoe te repliceren:
1. Zorg dat je langzaam internet hebt (kan door in Chrome in de DevTools bij Network op het dropdownmenu Online naar Slow 3G te zetten)
2. Ga naar een activiteit, klik op een gebruiker, en klik op Geld inleggen
3. Vul een bedrag in en klik twee keer snel op Inleg aanmaken

Verwacht resultaat:
Ondanks het twee keer klikken op de knop wordt er maar één keer een inleg aangemaakt.

Daadwerkelijk resultaat:
Er worden twee inleggen aangemaakt.

Mogelijke oplossingen:
1. Zorg in de front-end dat er maar één request naar de backend wordt gestuurd door na een klik de button te disablen, en enable de button pas weer als die request mislukt is.
2. Voeg een unique ID toe aan de inleg en zorg in de backend dat de inleg alleen wordt aangemaakt als die unique ID nog niet langs is gekomen.

**Comment by Matthijsy** [comment]
https://stackoverflow.com/a/39622399
