### ISSUE TITLE
Lock activities manually

### ISSUE THREAD

**Issue by wilco375** [csvalpha/sofia#398]
Right now, an activity expires and locks after 2 months. I think it would be nice to be able to lock it manually too as a treasurer.

**Comment by Matthijsy** [comment]
Would you like to lock them earlier? I think we could support this, but always lock the activity after 2 months (to prevent activities that do not get locked)

**Comment by wilco375** [comment]
Yes, that was my thought too. Then I can lock the activity after entering it in the accounting software and if I forget it it will still be locked after two months.
