### ISSUE TITLE
localhost versus 127.0.0.1:5000 when logging into sofia

### ISSUE THREAD

**Issue by Ellen-Wittingen** [csvalpha/sofia#783]
Run`bundle exec rails server` with or without `-p 5000`

Expected sofia to tell in the console to visit: http://localhost:5000 as that is also mentioned in the Readme.md
But it suggested http://127.0.0.1:5000 instead.

If you use sofia on 127.0.0.1 it puts 127.0.0.1 in the redirect url when logging in through amber UI, but amber ui/api does not accept 127.0.0.1 as a valid redirect url. So you should use sofia on localhost.

**Comment by guidojw** [comment]
This might be why I never got sofia working 😅

**Comment by lodewiges** [comment]
this works now with the development environment is this issue still relevant?
