### ISSUE TITLE
Cannot add money to the wasted ladder

### ISSUE THREAD

**Issue by Macanazo** [csvalpha/sofia#873]
### How to reproduce

1.go to S.O.F.I.A sign in and try to deposit money using ideal

2. Type in an eligible amount (€20>) and request to pay

What should happen is you get directed to the page where you decide with which bank you want to use.
What currently happens js this
![IMG-20230511-WA0019](https://github.com/csvalpha/sofia/assets/90518343/af49e441-30b0-4c74-a2ea-fd2b75ac9152)
*Optionally add some screenshots*

**Comment by wilco375** [comment]
Is this still an open issue? I was able to increase my balance without issues recently.
